// COMPANY ACTIONS TYPES
export const REGISTER_COMPANY_SUCCESS = "REGISTER_COMPANY_SUCCESS"
export const REGISTER_COMPANY_FAIL = "REGISTER_COMPANY_FAIL"
export const LOGIN_COMPANY_SUCCESS = "LOGIN_COMPANY_SUCCESS"
export const LOGIN_COMPANY_FAIL = "LOGIN_COMPANY_FAIL"
export const LOGOUT_COMPANY = "LOGOUT_COMPANY"
export const LOAD_COMPANY = "LOAD_COMPANY "
export const LOAD_COMPANY_FAIL  = "LOAD_COMPANY"

//CANDIDATE ACTIONS TYPES

export const REGISTER_CANDIDATE_SUCCESS = "REGISTER_CANDIDATE_SUCCESS"
export const REGISTER_CANDIDATE_FAIL = "REGISTER_CANDIDATE_FAIL"
export const LOGIN_CANDIDATE_SUCCESS = "LOGIN_CANDIDATE_SUCCESS"
export const LOGIN_CANDIDATE_FAIL = "LOGIN_CANDIDATE_FAIL"
export const LOGOUT_CANDIDATE = "LOGOUT_CANDIDATE"
export const LOAD_CANDIDATE = "LOAD_CANDIDATE "
export const LOAD_CANDIDATE_FAIL  = "LOAD_CANDIDATE"

// ALERT ACTIONS TYPES 

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
